#!/usr/bin/env node
// hoff-ui BrandPack generator (Law 5: deterministic Node, no AI).
//
// Reads branding.json + the vendored token CSS and emits the artifacts every
// consumer ingests — they NEVER read the raw tokens directly (Law 3a decoupling):
//   dist/brand.css            one stylesheet: spine + both themes, switch via data-theme
//   dist/brand.mjs            theme data + palettes as an ES module
//   dist/brand.manifest.json  the resolved BrandPack manifest
//   dist/chart-palette.json   ordered chart colours
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const read = (p) => readFileSync(join(root, p), "utf-8");

/** Build all artifacts in-memory. Pure: same inputs -> same outputs. */
export function generate() {
  const brand = JSON.parse(read("branding.json"));

  // brand.css = spine + each theme's css, concatenated in a stable order.
  const parts = [
    `/* GENERATED by @mycortex/hoff-ui generate.mjs — do not edit. Source: branding.json + tokens/. */`,
    read(brand.tokens),
  ];
  for (const name of Object.keys(brand.themes)) {
    parts.push(`/* --- theme: ${name} --- */`);
    parts.push(read(brand.themes[name].css));
  }
  const brandCss = parts.join("\n\n");

  const brandMjs =
    `// GENERATED by @mycortex/hoff-ui — do not edit.\n` +
    `export const brand = ${JSON.stringify(brand, null, 2)};\n` +
    `export const themes = brand.themes;\n` +
    `export const chartPalette = brand.chartPalette;\n` +
    `export const defaultTheme = brand.defaultTheme;\n` +
    `export default brand;\n`;

  return {
    "brand.css": brandCss,
    "brand.mjs": brandMjs,
    "brand.manifest.json": JSON.stringify(brand, null, 2) + "\n",
    "chart-palette.json": JSON.stringify(brand.chartPalette, null, 2) + "\n",
  };
}

/** Write artifacts to dist/. */
export function build(outDir = join(root, "dist")) {
  if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });
  const artifacts = generate();
  for (const [name, content] of Object.entries(artifacts)) {
    writeFileSync(join(outDir, name), content);
  }
  return Object.keys(artifacts);
}

// Run directly: node generate.mjs
if (import.meta.url === `file://${process.argv[1]}`) {
  const written = build();
  console.log(`hoff-ui: generated ${written.length} artifacts -> dist/ (${written.join(", ")})`);
}
